FROM rust:slim-bookworm AS builder
WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y pkg-config libssl-dev libpq-dev && rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

COPY backend .
RUN cargo build --release

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y ca-certificates libssl3 libpq5 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /usr/src/app/target/release/api /usr/local/bin/api
COPY --from=builder /usr/src/app/target/release/worker /usr/local/bin/worker
COPY --from=builder /usr/local/cargo/bin/diesel /usr/local/bin/diesel

COPY backend/store/diesel.toml .
COPY backend/store/migrations ./migrations

ENV RUST_LOG=info

EXPOSE 5000

CMD ["api"]